### PR TITLE
Looks for .app-config.meta files in workspace root if not in CWD

### LINKED ISSUE #25: Load app-config meta file from the root of a yarn workspace
Currently (v2), when looking for a meta file, app-config only looks at CWD. This will fail if you are using a workspace, and the meta file is at the root (since you're running a server in a subfolder of the root).

Meta file loading should:
1. Look at CWD
2. Go to a repository root (look up for `.git` folder)

This should be enough to support any arbitrary structure of repositories. Almost always, you'd want to use the same teamMembers across all subfolders. And if not, just create a meta file in the folders you want.

### PR DESCRIPTION
**Pull request by joelgallant**
This fixes #25. I didn't want to make complicated semantics w/ merging of files or arbitrary positions (look up until one is found or something like that).

### CODE REVIEW

**Comment by gregnr** [comment]
Have we thought about allowing `$extends` within a meta file? I would like to have a meta file in both the sub folder and workspace root, where sub folder defines `generate` functionality, and root defines secrets `teamMembers`, etc.

**Comment by joelgallant** [comment]
> Have we thought about allowing `$extends` within a meta file? I would like to have a meta file in both the sub folder and workspace root, where sub folder defines `generate` functionality, and root defines secrets `teamMembers`, etc.

Yeah, this is possible (it's just a matter of using the parsing extension). My initial thoughts around the new meta files were centred around simplifying the semantics as much as possible, but that may be misguided. To work around the limitations, hacks would end up being worse.

Specifically, passing parsing extensions to [read()](https://github.com/launchcodedev/app-config/blob/master/app-config/src/meta.ts#L37) is all that'd be required.

**Review by daniel-zarinski — APPROVED** [review]
Thank you for including this!

**Comment by gregnr** [comment]
@joelgallant I know this is already merged, but is this necessary any more now that we have #32?

**Comment by joelgallant** [comment]
I think it's a good default either way - it's almost certainly what a user would expect / hope to happen. The features seem orthogonal to me.

**Pull request merged**
