### PR TITLE
openpgp v5

### PR DESCRIPTION
**Pull request by dror-weiss**
I'm trying to make this library work with [bun](https://bun.sh/) instead of node, and I think the only thing in the way is openpgp v4.
Regardless of whether it will work, I submit a PR with some necessary changes to make it work with the significant API change.

* I have a single failing test in the expected value in `src/env-directive.test.ts:100:29 (expected: 2 received: 1)` that I don't think is related to my changes.

### CODE REVIEW

**Comment by dror-weiss** [comment]
@joelgallant, I hope you are the person to ping this PR to.

**Comment by daniel-heppner-ibigroup** [comment]
I think I am in need of this fix as well. Currently having trouble deploying to Vercel in a Remix project because of an issue with `asn1.js` missing, which I believe is a problem with openpgp v4. 
Also mentioned here: https://github.com/launchcodedev/app-config/issues/208#issuecomment-1211476858

**Comment by dror-weiss** [comment]
@daniel-heppner-ibigroup , I came back here due to lambda `asn1.js` error and was amazed to see this wasn't merged.
I'm not sure this repo is active anymore, which means we will need to find another solution.

**Comment by daniel-heppner-ibigroup** [comment]
@dror-weiss I ended up deciding it's better to just avoid these config libraries altogether, and just use Typescript for the configuration.

**Pull request closed without merging**
